version: "3.9"

services:

  plugin:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: plugin-runner
    image: obsidian-automation:v1
    volumes:
      - ${PWD}/test-vault:/app/test-vault
      - ${PWD}/watch:/app/watch
    network_mode: host
    command: ./plugin-dev-start.sh
#    command: /bin/bash
#    stdin_open: true # docker run -i
#    tty: true        # docker run -t
