version: "3.9"

services:

  plugin-dev:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: plugin-runner
    image: obsidian-automation:v1
    volumes:
      - ${PWD}:/app
    network_mode: host
    command: npm run dev
