version: "3.9"

services:

  plugin-dev:
    build:
      dockerfile: docker/Dockerfile
      context: ..
    container_name: plugin-runner
    image: obsidian-automation:v1
    volumes:
      - ${PWD}:/app
    network_mode: host
    command: ./docker/docker-command-dev.sh
#    command: /bin/bash
#    stdin_open: true # docker run -i
#    tty: true        # docker run -t
